<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CatPaisesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $paises = [
            ['CODIGO_PAIS' => 'AF', 'PAIS' => 'AFGANISTÁN', 'CLAVE_NACIONALIDAD' => 'AFG'],
            ['CODIGO_PAIS' => 'AL', 'PAIS' => 'ALBANIA', 'CLAVE_NACIONALIDAD' => 'ALB'],
            ['CODIGO_PAIS' => 'DE', 'PAIS' => 'ALEMANIA', 'CLAVE_NACIONALIDAD' => 'DEU'],
            ['CODIGO_PAIS' => 'AD', 'PAIS' => 'ANDORRA', 'CLAVE_NACIONALIDAD' => 'AND'],
            ['CODIGO_PAIS' => 'AO', 'PAIS' => 'ANGOLA', 'CLAVE_NACIONALIDAD' => 'AGO'],
            ['CODIGO_PAIS' => 'AI', 'PAIS' => 'ANGUILA', 'CLAVE_NACIONALIDAD' => 'AIA'],
            ['CODIGO_PAIS' => 'AQ', 'PAIS' => 'ANTÁRTIDA', 'CLAVE_NACIONALIDAD' => 'ATA'],
            ['CODIGO_PAIS' => 'AG', 'PAIS' => 'ANTIGUA Y BARBUDA', 'CLAVE_NACIONALIDAD' => 'ATG'],
            ['CODIGO_PAIS' => 'SA', 'PAIS' => 'ARABIA SAUDITA', 'CLAVE_NACIONALIDAD' => 'SAU'],
            ['CODIGO_PAIS' => 'DZ', 'PAIS' => 'ARGELIA', 'CLAVE_NACIONALIDAD' => 'DZA'],
            ['CODIGO_PAIS' => 'AR', 'PAIS' => 'ARGENTINA', 'CLAVE_NACIONALIDAD' => 'ARG'],
            ['CODIGO_PAIS' => 'AM', 'PAIS' => 'ARMENIA', 'CLAVE_NACIONALIDAD' => 'ARM'],
            ['CODIGO_PAIS' => 'AW', 'PAIS' => 'ARUBA', 'CLAVE_NACIONALIDAD' => 'ABW'],
            ['CODIGO_PAIS' => 'AU', 'PAIS' => 'AUSTRALIA', 'CLAVE_NACIONALIDAD' => 'AUS'],
            ['CODIGO_PAIS' => 'AT', 'PAIS' => 'AUSTRIA', 'CLAVE_NACIONALIDAD' => 'AUT'],
            ['CODIGO_PAIS' => 'AZ', 'PAIS' => 'AZERBAIYÁN', 'CLAVE_NACIONALIDAD' => 'AZE'],
            ['CODIGO_PAIS' => 'BS', 'PAIS' => 'BAHAMAS', 'CLAVE_NACIONALIDAD' => 'BHS'],
            ['CODIGO_PAIS' => 'BD', 'PAIS' => 'BANGLADÉS', 'CLAVE_NACIONALIDAD' => 'BGD'],
            ['CODIGO_PAIS' => 'BB', 'PAIS' => 'BARBADOS', 'CLAVE_NACIONALIDAD' => 'BRB'],
            ['CODIGO_PAIS' => 'BH', 'PAIS' => 'BARÉIN', 'CLAVE_NACIONALIDAD' => 'BHR'],
            ['CODIGO_PAIS' => 'BE', 'PAIS' => 'BÉLGICA', 'CLAVE_NACIONALIDAD' => 'BEL'],
            ['CODIGO_PAIS' => 'BZ', 'PAIS' => 'BELICE', 'CLAVE_NACIONALIDAD' => 'BLZ'],
            ['CODIGO_PAIS' => 'BJ', 'PAIS' => 'BENÍN', 'CLAVE_NACIONALIDAD' => 'BEN'],
            ['CODIGO_PAIS' => 'BM', 'PAIS' => 'BERMUDAS', 'CLAVE_NACIONALIDAD' => 'BMU'],
            ['CODIGO_PAIS' => 'BY', 'PAIS' => 'BIELORRUSIA', 'CLAVE_NACIONALIDAD' => 'BLR'],
            ['CODIGO_PAIS' => 'MM', 'PAIS' => 'BIRMANIA / MYANMAR', 'CLAVE_NACIONALIDAD' => 'MMR'],
            ['CODIGO_PAIS' => 'BO', 'PAIS' => 'BOLIVIA', 'CLAVE_NACIONALIDAD' => 'BOL'],
            ['CODIGO_PAIS' => 'BQ', 'PAIS' => 'BONAIRE, SAN EUSTAQUIO Y SABA', 'CLAVE_NACIONALIDAD' => 'BES'],
            ['CODIGO_PAIS' => 'BA', 'PAIS' => 'BOSNIA Y HERZEGOVINA', 'CLAVE_NACIONALIDAD' => 'BIH'],
            ['CODIGO_PAIS' => 'BW', 'PAIS' => 'BOTSUANA', 'CLAVE_NACIONALIDAD' => 'BWA'],
            ['CODIGO_PAIS' => 'BR', 'PAIS' => 'BRASIL', 'CLAVE_NACIONALIDAD' => 'BRA'],
            ['CODIGO_PAIS' => 'BN', 'PAIS' => 'BRUNÉI', 'CLAVE_NACIONALIDAD' => 'BRN'],
            ['CODIGO_PAIS' => 'BG', 'PAIS' => 'BULGARIA', 'CLAVE_NACIONALIDAD' => 'BGR'],
            ['CODIGO_PAIS' => 'BF', 'PAIS' => 'BURKINA FASO', 'CLAVE_NACIONALIDAD' => 'BFA'],
            ['CODIGO_PAIS' => 'BI', 'PAIS' => 'BURUNDI', 'CLAVE_NACIONALIDAD' => 'BDI'],
            ['CODIGO_PAIS' => 'BT', 'PAIS' => 'BUTÁN', 'CLAVE_NACIONALIDAD' => 'BTN'],
            ['CODIGO_PAIS' => 'CV', 'PAIS' => 'CABO VERDE', 'CLAVE_NACIONALIDAD' => 'CPV'],
            ['CODIGO_PAIS' => 'KH', 'PAIS' => 'CAMBOYA', 'CLAVE_NACIONALIDAD' => 'KHM'],
            ['CODIGO_PAIS' => 'CM', 'PAIS' => 'CAMERÚN', 'CLAVE_NACIONALIDAD' => 'CMR'],
            ['CODIGO_PAIS' => 'CA', 'PAIS' => 'CANADÁ', 'CLAVE_NACIONALIDAD' => 'CAN'],
            ['CODIGO_PAIS' => 'QA', 'PAIS' => 'CATAR', 'CLAVE_NACIONALIDAD' => 'QAT'],
            ['CODIGO_PAIS' => 'TD', 'PAIS' => 'CHAD', 'CLAVE_NACIONALIDAD' => 'TCD'],
            ['CODIGO_PAIS' => 'CL', 'PAIS' => 'CHILE', 'CLAVE_NACIONALIDAD' => 'CHL'],
            ['CODIGO_PAIS' => 'CN', 'PAIS' => 'CHINA', 'CLAVE_NACIONALIDAD' => 'CHN'],
            ['CODIGO_PAIS' => 'CY', 'PAIS' => 'CHIPRE', 'CLAVE_NACIONALIDAD' => 'CYP'],
            ['CODIGO_PAIS' => 'CO', 'PAIS' => 'COLOMBIA', 'CLAVE_NACIONALIDAD' => 'COL'],
            ['CODIGO_PAIS' => 'KM', 'PAIS' => 'COMORAS', 'CLAVE_NACIONALIDAD' => 'COM'],
            ['CODIGO_PAIS' => 'KP', 'PAIS' => 'COREA DEL NORTE', 'CLAVE_NACIONALIDAD' => 'PRK'],
            ['CODIGO_PAIS' => 'KR', 'PAIS' => 'COREA DEL SUR', 'CLAVE_NACIONALIDAD' => 'KOR'],
            ['CODIGO_PAIS' => 'CI', 'PAIS' => 'COSTA DE MARFIL', 'CLAVE_NACIONALIDAD' => 'CIV'],
            ['CODIGO_PAIS' => 'CR', 'PAIS' => 'COSTA RICA', 'CLAVE_NACIONALIDAD' => 'CRI'],
            ['CODIGO_PAIS' => 'HR', 'PAIS' => 'CROACIA', 'CLAVE_NACIONALIDAD' => 'HRV'],
            ['CODIGO_PAIS' => 'CU', 'PAIS' => 'CUBA', 'CLAVE_NACIONALIDAD' => 'CUB'],
            ['CODIGO_PAIS' => 'CW', 'PAIS' => 'CURAZAO', 'CLAVE_NACIONALIDAD' => 'CUW'],
            ['CODIGO_PAIS' => 'DK', 'PAIS' => 'DINAMARCA', 'CLAVE_NACIONALIDAD' => 'DNK'],
            ['CODIGO_PAIS' => 'DM', 'PAIS' => 'DOMINICA', 'CLAVE_NACIONALIDAD' => 'DMA'],
            ['CODIGO_PAIS' => 'EC', 'PAIS' => 'ECUADOR', 'CLAVE_NACIONALIDAD' => 'ECU'],
            ['CODIGO_PAIS' => 'EG', 'PAIS' => 'EGIPTO', 'CLAVE_NACIONALIDAD' => 'EGY'],
            ['CODIGO_PAIS' => 'SV', 'PAIS' => 'EL SALVADOR', 'CLAVE_NACIONALIDAD' => 'SLV'],
            ['CODIGO_PAIS' => 'AE', 'PAIS' => 'EMIRATOS ÁRABES UNIDOS', 'CLAVE_NACIONALIDAD' => 'ARE'],
            ['CODIGO_PAIS' => 'ER', 'PAIS' => 'ERITREA', 'CLAVE_NACIONALIDAD' => 'ERI'],
            ['CODIGO_PAIS' => 'SK', 'PAIS' => 'ESLOVAQUIA', 'CLAVE_NACIONALIDAD' => 'SVK'],
            ['CODIGO_PAIS' => 'SI', 'PAIS' => 'ESLOVENIA', 'CLAVE_NACIONALIDAD' => 'SVN'],
            ['CODIGO_PAIS' => 'ES', 'PAIS' => 'ESPAÑA', 'CLAVE_NACIONALIDAD' => 'ESP'],
            ['CODIGO_PAIS' => 'US', 'PAIS' => 'ESTADOS UNIDOS', 'CLAVE_NACIONALIDAD' => 'USA'],
            ['CODIGO_PAIS' => 'EE', 'PAIS' => 'ESTONIA', 'CLAVE_NACIONALIDAD' => 'EST'],
            ['CODIGO_PAIS' => 'SZ', 'PAIS' => 'ESWATINI / SUAZILANDIA', 'CLAVE_NACIONALIDAD' => 'SWZ'],
            ['CODIGO_PAIS' => 'ET', 'PAIS' => 'ETIOPÍA', 'CLAVE_NACIONALIDAD' => 'ETH'],
            ['CODIGO_PAIS' => 'PH', 'PAIS' => 'FILIPINAS', 'CLAVE_NACIONALIDAD' => 'PHL'],
            ['CODIGO_PAIS' => 'FI', 'PAIS' => 'FINLANDIA', 'CLAVE_NACIONALIDAD' => 'FIN'],
            ['CODIGO_PAIS' => 'FJ', 'PAIS' => 'FIYI', 'CLAVE_NACIONALIDAD' => 'FJI'],
            ['CODIGO_PAIS' => 'FR', 'PAIS' => 'FRANCIA', 'CLAVE_NACIONALIDAD' => 'FRA'],
            ['CODIGO_PAIS' => 'GA', 'PAIS' => 'GABÓN', 'CLAVE_NACIONALIDAD' => 'GAB'],
            ['CODIGO_PAIS' => 'GM', 'PAIS' => 'GAMBIA', 'CLAVE_NACIONALIDAD' => 'GMB'],
            ['CODIGO_PAIS' => 'GE', 'PAIS' => 'GEORGIA', 'CLAVE_NACIONALIDAD' => 'GEO'],
            ['CODIGO_PAIS' => 'GH', 'PAIS' => 'GHANA', 'CLAVE_NACIONALIDAD' => 'GHA'],
            ['CODIGO_PAIS' => 'GI', 'PAIS' => 'GIBRALTAR', 'CLAVE_NACIONALIDAD' => 'GIB'],
            ['CODIGO_PAIS' => 'GD', 'PAIS' => 'GRANADA', 'CLAVE_NACIONALIDAD' => 'GRD'],
            ['CODIGO_PAIS' => 'GR', 'PAIS' => 'GRECIA', 'CLAVE_NACIONALIDAD' => 'GRC'],
            ['CODIGO_PAIS' => 'GL', 'PAIS' => 'GROENLANDIA', 'CLAVE_NACIONALIDAD' => 'GRL'],
            ['CODIGO_PAIS' => 'GP', 'PAIS' => 'GUADALUPE', 'CLAVE_NACIONALIDAD' => 'GLP'],
            ['CODIGO_PAIS' => 'GU', 'PAIS' => 'GUAM', 'CLAVE_NACIONALIDAD' => 'GUM'],
            ['CODIGO_PAIS' => 'GT', 'PAIS' => 'GUATEMALA', 'CLAVE_NACIONALIDAD' => 'GTM'],
            ['CODIGO_PAIS' => 'GF', 'PAIS' => 'GUAYANA FRANCESA', 'CLAVE_NACIONALIDAD' => 'GUF'],
            ['CODIGO_PAIS' => 'GG', 'PAIS' => 'GUERNSEY', 'CLAVE_NACIONALIDAD' => 'GGY'],
            ['CODIGO_PAIS' => 'GN', 'PAIS' => 'GUINEA', 'CLAVE_NACIONALIDAD' => 'GIN'],
            ['CODIGO_PAIS' => 'GW', 'PAIS' => 'GUINEA-BISÁU', 'CLAVE_NACIONALIDAD' => 'GNB'],
            ['CODIGO_PAIS' => 'GQ', 'PAIS' => 'GUINEA ECUATORIAL', 'CLAVE_NACIONALIDAD' => 'GNQ'],
            ['CODIGO_PAIS' => 'GY', 'PAIS' => 'GUYANA', 'CLAVE_NACIONALIDAD' => 'GUY'],
            ['CODIGO_PAIS' => 'HT', 'PAIS' => 'HAITÍ', 'CLAVE_NACIONALIDAD' => 'HTI'],
            ['CODIGO_PAIS' => 'HN', 'PAIS' => 'HONDURAS', 'CLAVE_NACIONALIDAD' => 'HND'],
            ['CODIGO_PAIS' => 'HK', 'PAIS' => 'HONG KONG', 'CLAVE_NACIONALIDAD' => 'HKG'],
            ['CODIGO_PAIS' => 'HU', 'PAIS' => 'HUNGRÍA', 'CLAVE_NACIONALIDAD' => 'HUN'],
            ['CODIGO_PAIS' => 'IN', 'PAIS' => 'INDIA', 'CLAVE_NACIONALIDAD' => 'IND'],
            ['CODIGO_PAIS' => 'ID', 'PAIS' => 'INDONESIA', 'CLAVE_NACIONALIDAD' => 'IDN'],
            ['CODIGO_PAIS' => 'IQ', 'PAIS' => 'IRAK', 'CLAVE_NACIONALIDAD' => 'IRQ'],
            ['CODIGO_PAIS' => 'IR', 'PAIS' => 'IRÁN', 'CLAVE_NACIONALIDAD' => 'IRN'],
            ['CODIGO_PAIS' => 'IE', 'PAIS' => 'IRLANDA', 'CLAVE_NACIONALIDAD' => 'IRL'],
            ['CODIGO_PAIS' => 'IM', 'PAIS' => 'ISLA DE MAN', 'CLAVE_NACIONALIDAD' => 'IMN'],
            ['CODIGO_PAIS' => 'IS', 'PAIS' => 'ISLANDIA', 'CLAVE_NACIONALIDAD' => 'ISL'],
            ['CODIGO_PAIS' => 'AI', 'PAIS' => 'ISLAS CAIMÁN', 'CLAVE_NACIONALIDAD' => 'CYM'],
            ['CODIGO_PAIS' => 'CK', 'PAIS' => 'ISLAS COOK', 'CLAVE_NACIONALIDAD' => 'COK'],
            ['CODIGO_PAIS' => 'FO', 'PAIS' => 'ISLAS FEROE', 'CLAVE_NACIONALIDAD' => 'FRO'],
            ['CODIGO_PAIS' => 'GS', 'PAIS' => 'ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR', 'CLAVE_NACIONALIDAD' => 'SGS'],
            ['CODIGO_PAIS' => 'FK', 'PAIS' => 'ISLAS MALVINAS', 'CLAVE_NACIONALIDAD' => 'FLK'],
            ['CODIGO_PAIS' => 'MP', 'PAIS' => 'ISLAS MARIANAS DEL NORTE', 'CLAVE_NACIONALIDAD' => 'MNP'],
            ['CODIGO_PAIS' => 'MH', 'PAIS' => 'ISLAS MARSHALL', 'CLAVE_NACIONALIDAD' => 'MHL'],
            ['CODIGO_PAIS' => 'PN', 'PAIS' => 'ISLAS PITCAIRN', 'CLAVE_NACIONALIDAD' => 'PCN'],
            ['CODIGO_PAIS' => 'SB', 'PAIS' => 'ISLAS SALOMÓN', 'CLAVE_NACIONALIDAD' => 'SLB'],
            ['CODIGO_PAIS' => 'TC', 'PAIS' => 'ISLAS TURCAS Y CAICOS', 'CLAVE_NACIONALIDAD' => 'TCA'],
            ['CODIGO_PAIS' => 'VG', 'PAIS' => 'ISLAS VÍRGENES BRITÁNICAS', 'CLAVE_NACIONALIDAD' => 'VGB'],
            ['CODIGO_PAIS' => 'VI', 'PAIS' => 'ISLAS VÍRGENES DE LOS ESTADOS UNIDOS', 'CLAVE_NACIONALIDAD' => 'VIR'],
            ['CODIGO_PAIS' => 'IL', 'PAIS' => 'ISRAEL', 'CLAVE_NACIONALIDAD' => 'ISR'],
            ['CODIGO_PAIS' => 'IT', 'PAIS' => 'ITALIA', 'CLAVE_NACIONALIDAD' => 'ITA'],
            ['CODIGO_PAIS' => 'JM', 'PAIS' => 'JAMAICA', 'CLAVE_NACIONALIDAD' => 'JAM'],
            ['CODIGO_PAIS' => 'JP', 'PAIS' => 'JAPÓN', 'CLAVE_NACIONALIDAD' => 'JPN'],
            ['CODIGO_PAIS' => 'JE', 'PAIS' => 'JERSEY', 'CLAVE_NACIONALIDAD' => 'JEY'],
            ['CODIGO_PAIS' => 'JO', 'PAIS' => 'JORDANIA', 'CLAVE_NACIONALIDAD' => 'JOR'],
            ['CODIGO_PAIS' => 'KZ', 'PAIS' => 'KAZAJISTÁN', 'CLAVE_NACIONALIDAD' => 'KAZ'],
            ['CODIGO_PAIS' => 'KE', 'PAIS' => 'KENIA', 'CLAVE_NACIONALIDAD' => 'KEN'],
            ['CODIGO_PAIS' => 'KG', 'PAIS' => 'KIRGUISTÁN', 'CLAVE_NACIONALIDAD' => 'KGZ'],
            ['CODIGO_PAIS' => 'KI', 'PAIS' => 'KIRIBATI', 'CLAVE_NACIONALIDAD' => 'KIR'],
            ['CODIGO_PAIS' => 'KW', 'PAIS' => 'KUWAIT', 'CLAVE_NACIONALIDAD' => 'KWT'],
            ['CODIGO_PAIS' => 'LA', 'PAIS' => 'LAOS', 'CLAVE_NACIONALIDAD' => 'LAO'],
            ['CODIGO_PAIS' => 'LS', 'PAIS' => 'LESOTO', 'CLAVE_NACIONALIDAD' => 'LSO'],
            ['CODIGO_PAIS' => 'LV', 'PAIS' => 'LETONIA', 'CLAVE_NACIONALIDAD' => 'LVA'],
            ['CODIGO_PAIS' => 'LB', 'PAIS' => 'LÍBANO', 'CLAVE_NACIONALIDAD' => 'LBN'],
            ['CODIGO_PAIS' => 'LR', 'PAIS' => 'LIBERIA', 'CLAVE_NACIONALIDAD' => 'LBR'],
            ['CODIGO_PAIS' => 'LY', 'PAIS' => 'LIBIA', 'CLAVE_NACIONALIDAD' => 'LBY'],
            ['CODIGO_PAIS' => 'LI', 'PAIS' => 'LIECHTENSTEIN', 'CLAVE_NACIONALIDAD' => 'LIE'],
            ['CODIGO_PAIS' => 'LT', 'PAIS' => 'LITUANIA', 'CLAVE_NACIONALIDAD' => 'LTU'],
            ['CODIGO_PAIS' => 'LU', 'PAIS' => 'LUXEMBURGO', 'CLAVE_NACIONALIDAD' => 'LUX'],
            ['CODIGO_PAIS' => 'MO', 'PAIS' => 'MACAO', 'CLAVE_NACIONALIDAD' => 'MAC'],
            ['CODIGO_PAIS' => 'MK', 'PAIS' => 'MACEDONIA DEL NORTE', 'CLAVE_NACIONALIDAD' => 'MKD'],
            ['CODIGO_PAIS' => 'MG', 'PAIS' => 'MADAGASCAR', 'CLAVE_NACIONALIDAD' => 'MDG'],
            ['CODIGO_PAIS' => 'MY', 'PAIS' => 'MALASIA', 'CLAVE_NACIONALIDAD' => 'MYS'],
            ['CODIGO_PAIS' => 'MW', 'PAIS' => 'MALAUI', 'CLAVE_NACIONALIDAD' => 'MWI'],
            ['CODIGO_PAIS' => 'MV', 'PAIS' => 'MALDIVAS', 'CLAVE_NACIONALIDAD' => 'MDV'],
            ['CODIGO_PAIS' => 'ML', 'PAIS' => 'MALÍ', 'CLAVE_NACIONALIDAD' => 'MLI'],
            ['CODIGO_PAIS' => 'MT', 'PAIS' => 'MALTA', 'CLAVE_NACIONALIDAD' => 'MLT'],
            ['CODIGO_PAIS' => 'MA', 'PAIS' => 'MARRUECOS', 'CLAVE_NACIONALIDAD' => 'MAR'],
            ['CODIGO_PAIS' => 'MQ', 'PAIS' => 'MARTINICA', 'CLAVE_NACIONALIDAD' => 'MTQ'],
            ['CODIGO_PAIS' => 'MU', 'PAIS' => 'MAURICIO', 'CLAVE_NACIONALIDAD' => 'MUS'],
            ['CODIGO_PAIS' => 'MR', 'PAIS' => 'MAURITANIA', 'CLAVE_NACIONALIDAD' => 'MRT'],
            ['CODIGO_PAIS' => 'YT', 'PAIS' => 'MAYOTTE', 'CLAVE_NACIONALIDAD' => 'MYT'],
            ['CODIGO_PAIS' => 'MX', 'PAIS' => 'MÉXICO', 'CLAVE_NACIONALIDAD' => 'MEX'],
            ['CODIGO_PAIS' => 'FM', 'PAIS' => 'MICRONESIA', 'CLAVE_NACIONALIDAD' => 'FSM'],
            ['CODIGO_PAIS' => 'MD', 'PAIS' => 'MOLDAVIA', 'CLAVE_NACIONALIDAD' => 'MDA'],
            ['CODIGO_PAIS' => 'MC', 'PAIS' => 'MÓNACO', 'CLAVE_NACIONALIDAD' => 'MCO'],
            ['CODIGO_PAIS' => 'MN', 'PAIS' => 'MONGOLIA', 'CLAVE_NACIONALIDAD' => 'MNG'],
            ['CODIGO_PAIS' => 'ME', 'PAIS' => 'MONTENEGRO', 'CLAVE_NACIONALIDAD' => 'MNE'],
            ['CODIGO_PAIS' => 'MS', 'PAIS' => 'MONTSERRAT', 'CLAVE_NACIONALIDAD' => 'MSR'],
            ['CODIGO_PAIS' => 'MZ', 'PAIS' => 'MOZAMBIQUE', 'CLAVE_NACIONALIDAD' => 'MOZ'],
            ['CODIGO_PAIS' => 'NA', 'PAIS' => 'NAMIBIA', 'CLAVE_NACIONALIDAD' => 'NAM'],
            ['CODIGO_PAIS' => 'NR', 'PAIS' => 'NAURU', 'CLAVE_NACIONALIDAD' => 'NRU'],
            ['CODIGO_PAIS' => 'NP', 'PAIS' => 'NEPAL', 'CLAVE_NACIONALIDAD' => 'NPL'],
            ['CODIGO_PAIS' => 'NI', 'PAIS' => 'NICARAGUA', 'CLAVE_NACIONALIDAD' => 'NIC'],
            ['CODIGO_PAIS' => 'NE', 'PAIS' => 'NÍGER', 'CLAVE_NACIONALIDAD' => 'NER'],
            ['CODIGO_PAIS' => 'NG', 'PAIS' => 'NIGERIA', 'CLAVE_NACIONALIDAD' => 'NGA'],
            ['CODIGO_PAIS' => 'NU', 'PAIS' => 'NIUE', 'CLAVE_NACIONALIDAD' => 'NIU'],
            ['CODIGO_PAIS' => 'NO', 'PAIS' => 'NORUEGA', 'CLAVE_NACIONALIDAD' => 'NOR'],
            ['CODIGO_PAIS' => 'NC', 'PAIS' => 'NUEVA CALEDONIA', 'CLAVE_NACIONALIDAD' => 'NCL'],
            ['CODIGO_PAIS' => 'NZ', 'PAIS' => 'NUEVA ZELANDA', 'CLAVE_NACIONALIDAD' => 'NZL'],
            ['CODIGO_PAIS' => 'OM', 'PAIS' => 'OMÁN', 'CLAVE_NACIONALIDAD' => 'OMN'],
            ['CODIGO_PAIS' => 'NL', 'PAIS' => 'PAÍSES BAJOS', 'CLAVE_NACIONALIDAD' => 'NLD'],
            ['CODIGO_PAIS' => 'PK', 'PAIS' => 'PAKISTÁN', 'CLAVE_NACIONALIDAD' => 'PAK'],
            ['CODIGO_PAIS' => 'PW', 'PAIS' => 'PALAOS', 'CLAVE_NACIONALIDAD' => 'PLW'],
            ['CODIGO_PAIS' => 'PS', 'PAIS' => 'PALESTINA', 'CLAVE_NACIONALIDAD' => 'PSE'],
            ['CODIGO_PAIS' => 'PA', 'PAIS' => 'PANAMÁ', 'CLAVE_NACIONALIDAD' => 'PAN'],
            ['CODIGO_PAIS' => 'PG', 'PAIS' => 'PAPÚA NUEVA GUINEA', 'CLAVE_NACIONALIDAD' => 'PNG'],
            ['CODIGO_PAIS' => 'PY', 'PAIS' => 'PARAGUAY', 'CLAVE_NACIONALIDAD' => 'PRY'],
            ['CODIGO_PAIS' => 'PE', 'PAIS' => 'PERÚ', 'CLAVE_NACIONALIDAD' => 'PER'],
            ['CODIGO_PAIS' => 'PF', 'PAIS' => 'POLINESIA FRANCESA', 'CLAVE_NACIONALIDAD' => 'PYF'],
            ['CODIGO_PAIS' => 'PL', 'PAIS' => 'POLONIA', 'CLAVE_NACIONALIDAD' => 'POL'],
            ['CODIGO_PAIS' => 'PT', 'PAIS' => 'PORTUGAL', 'CLAVE_NACIONALIDAD' => 'PRT'],
            ['CODIGO_PAIS' => 'PR', 'PAIS' => 'PUERTO RICO', 'CLAVE_NACIONALIDAD' => 'PRI'],
            ['CODIGO_PAIS' => 'GB', 'PAIS' => 'REINO UNIDO', 'CLAVE_NACIONALIDAD' => 'GBR'],
            ['CODIGO_PAIS' => 'CF', 'PAIS' => 'REPÚBLICA CENTROAFRICANA', 'CLAVE_NACIONALIDAD' => 'CAF'],
            ['CODIGO_PAIS' => 'CZ', 'PAIS' => 'REPÚBLICA CHECA', 'CLAVE_NACIONALIDAD' => 'CZE'],
            ['CODIGO_PAIS' => 'CG', 'PAIS' => 'REPÚBLICA DEL CONGO', 'CLAVE_NACIONALIDAD' => 'COG'],
            ['CODIGO_PAIS' => 'CD', 'PAIS' => 'REPÚBLICA DEMOCRÁTICA DEL CONGO', 'CLAVE_NACIONALIDAD' => 'COD'],
            ['CODIGO_PAIS' => 'DO', 'PAIS' => 'REPÚBLICA DOMINICANA', 'CLAVE_NACIONALIDAD' => 'DOM'],
            ['CODIGO_PAIS' => 'RE', 'PAIS' => 'REUNIÓN', 'CLAVE_NACIONALIDAD' => 'REU'],
            ['CODIGO_PAIS' => 'RW', 'PAIS' => 'RUANDA', 'CLAVE_NACIONALIDAD' => 'RWA'],
            ['CODIGO_PAIS' => 'RO', 'PAIS' => 'RUMANIA', 'CLAVE_NACIONALIDAD' => 'ROU'],
            ['CODIGO_PAIS' => 'RU', 'PAIS' => 'RUSIA', 'CLAVE_NACIONALIDAD' => 'RUS'],
            ['CODIGO_PAIS' => 'EH', 'PAIS' => 'SAHARA OCCIDENTAL', 'CLAVE_NACIONALIDAD' => 'ESH'],
            ['CODIGO_PAIS' => 'WS', 'PAIS' => 'SAMOA', 'CLAVE_NACIONALIDAD' => 'WSM'],
            ['CODIGO_PAIS' => 'AS', 'PAIS' => 'SAMOA AMERICANA', 'CLAVE_NACIONALIDAD' => 'ASM'],
            ['CODIGO_PAIS' => 'BL', 'PAIS' => 'SAN BARTOLOMÉ', 'CLAVE_NACIONALIDAD' => 'BLM'],
            ['CODIGO_PAIS' => 'KN', 'PAIS' => 'SAN CRISTÓBAL Y NIEVES', 'CLAVE_NACIONALIDAD' => 'KNA'],
            ['CODIGO_PAIS' => 'SM', 'PAIS' => 'SAN MARINO', 'CLAVE_NACIONALIDAD' => 'SMR'],
            ['CODIGO_PAIS' => 'MF', 'PAIS' => 'SAN MARTÍN', 'CLAVE_NACIONALIDAD' => 'MAF'],
            ['CODIGO_PAIS' => 'PM', 'PAIS' => 'SAN PEDRO Y MIQUELÓN', 'CLAVE_NACIONALIDAD' => 'SPM'],
            ['CODIGO_PAIS' => 'VC', 'PAIS' => 'SAN VICENTE Y LAS GRANADINAS', 'CLAVE_NACIONALIDAD' => 'VCT'],
            ['CODIGO_PAIS' => 'SH', 'PAIS' => 'SANTA ELENA, ASCENSIÓN Y TRISTÁN DE ACUÑA', 'CLAVE_NACIONALIDAD' => 'SHN'],
            ['CODIGO_PAIS' => 'LC', 'PAIS' => 'SANTA LUCÍA', 'CLAVE_NACIONALIDAD' => 'LCA'],
            ['CODIGO_PAIS' => 'ST', 'PAIS' => 'SANTO TOMÉ Y PRÍCIPE', 'CLAVE_NACIONALIDAD' => 'STP'],
            ['CODIGO_PAIS' => 'SN', 'PAIS' => 'SENEGAL', 'CLAVE_NACIONALIDAD' => 'SEN'],
            ['CODIGO_PAIS' => 'RS', 'PAIS' => 'SERBIA', 'CLAVE_NACIONALIDAD' => 'SRB'],
            ['CODIGO_PAIS' => 'SC', 'PAIS' => 'SEYCHELLES', 'CLAVE_NACIONALIDAD' => 'SYC'],
            ['CODIGO_PAIS' => 'SL', 'PAIS' => 'SIERRA LEONA', 'CLAVE_NACIONALIDAD' => 'SLE'],
            ['CODIGO_PAIS' => 'SG', 'PAIS' => 'SINGAPUR', 'CLAVE_NACIONALIDAD' => 'SGP'],
            ['CODIGO_PAIS' => 'SX', 'PAIS' => 'SINT MAARTEN', 'CLAVE_NACIONALIDAD' => 'SXM'],
            ['CODIGO_PAIS' => 'SY', 'PAIS' => 'SIRIA', 'CLAVE_NACIONALIDAD' => 'SYR'],
            ['CODIGO_PAIS' => 'SO', 'PAIS' => 'SOMALIA', 'CLAVE_NACIONALIDAD' => 'SOM'],
            ['CODIGO_PAIS' => 'LK', 'PAIS' => 'SRI LANKA', 'CLAVE_NACIONALIDAD' => 'LKA'],
            ['CODIGO_PAIS' => 'SD', 'PAIS' => 'SUDÁN', 'CLAVE_NACIONALIDAD' => 'SDN'],
            ['CODIGO_PAIS' => 'SS', 'PAIS' => 'SUDÁN DEL SUR', 'CLAVE_NACIONALIDAD' => 'SSD'],
            ['CODIGO_PAIS' => 'SE', 'PAIS' => 'SUECIA', 'CLAVE_NACIONALIDAD' => 'SWE'],
            ['CODIGO_PAIS' => 'CH', 'PAIS' => 'SUIZA', 'CLAVE_NACIONALIDAD' => 'CHE'],
            ['CODIGO_PAIS' => 'SR', 'PAIS' => 'SURINAM', 'CLAVE_NACIONALIDAD' => 'SUR'],
            ['CODIGO_PAIS' => 'SJ', 'PAIS' => 'SVALBARD Y JAN MAYEN', 'CLAVE_NACIONALIDAD' => 'SJM'],
            ['CODIGO_PAIS' => 'TH', 'PAIS' => 'TAILANDIA', 'CLAVE_NACIONALIDAD' => 'THA'],
            ['CODIGO_PAIS' => 'TW', 'PAIS' => 'TAIWÁN', 'CLAVE_NACIONALIDAD' => 'TWN'],
            ['CODIGO_PAIS' => 'TZ', 'PAIS' => 'TANZANIA', 'CLAVE_NACIONALIDAD' => 'TZA'],
            ['CODIGO_PAIS' => 'TJ', 'PAIS' => 'TAYIKISTÁN', 'CLAVE_NACIONALIDAD' => 'TJK'],
            ['CODIGO_PAIS' => 'IO', 'PAIS' => 'TERRITORIO BRITÁNICO DEL OCÉANO ÍNDICO', 'CLAVE_NACIONALIDAD' => 'IOT'],
            ['CODIGO_PAIS' => 'TF', 'PAIS' => 'TERRITORIOS AUSTRALES FRANCESES', 'CLAVE_NACIONALIDAD' => 'ATF'],
            ['CODIGO_PAIS' => 'TL', 'PAIS' => 'TIMOR ORIENTAL', 'CLAVE_NACIONALIDAD' => 'TLS'],
            ['CODIGO_PAIS' => 'TG', 'PAIS' => 'TOGO', 'CLAVE_NACIONALIDAD' => 'TGO'],
            ['CODIGO_PAIS' => 'TK', 'PAIS' => 'TOKELAU', 'CLAVE_NACIONALIDAD' => 'TKL'],
            ['CODIGO_PAIS' => 'TO', 'PAIS' => 'TONGA', 'CLAVE_NACIONALIDAD' => 'TON'],
            ['CODIGO_PAIS' => 'TT', 'PAIS' => 'TRINIDAD Y TOBAGO', 'CLAVE_NACIONALIDAD' => 'TTO'],
            ['CODIGO_PAIS' => 'TN', 'PAIS' => 'TÚNEZ', 'CLAVE_NACIONALIDAD' => 'TUN'],
            ['CODIGO_PAIS' => 'TM', 'PAIS' => 'TURKMENISTÁN', 'CLAVE_NACIONALIDAD' => 'TKM'],
            ['CODIGO_PAIS' => 'TR', 'PAIS' => 'TURQUÍA', 'CLAVE_NACIONALIDAD' => 'TUR'],
            ['CODIGO_PAIS' => 'TV', 'PAIS' => 'TUVALU', 'CLAVE_NACIONALIDAD' => 'TUV'],
            ['CODIGO_PAIS' => 'UA', 'PAIS' => 'UCRANIA', 'CLAVE_NACIONALIDAD' => 'UKR'],
            ['CODIGO_PAIS' => 'UG', 'PAIS' => 'UGANDA', 'CLAVE_NACIONALIDAD' => 'UGA'],
            ['CODIGO_PAIS' => 'UY', 'PAIS' => 'URUGUAY', 'CLAVE_NACIONALIDAD' => 'URY'],
            ['CODIGO_PAIS' => 'UZ', 'PAIS' => 'UZBEKISTÁN', 'CLAVE_NACIONALIDAD' => 'UZB'],
            ['CODIGO_PAIS' => 'VU', 'PAIS' => 'VANUATU', 'CLAVE_NACIONALIDAD' => 'VUT'],
            ['CODIGO_PAIS' => 'VA', 'PAIS' => 'VATICANO', 'CLAVE_NACIONALIDAD' => 'VAT'],
            ['CODIGO_PAIS' => 'VE', 'PAIS' => 'VENEZUELA', 'CLAVE_NACIONALIDAD' => 'VEN'],
            ['CODIGO_PAIS' => 'VN', 'PAIS' => 'VIETNAM', 'CLAVE_NACIONALIDAD' => 'VNM'],
            ['CODIGO_PAIS' => 'WF', 'PAIS' => 'WALLIS Y FUTUNA', 'CLAVE_NACIONALIDAD' => 'WLF'],
            ['CODIGO_PAIS' => 'YE', 'PAIS' => 'YEMEN', 'CLAVE_NACIONALIDAD' => 'YEM'],
            ['CODIGO_PAIS' => 'DJ', 'PAIS' => 'YIBUTI', 'CLAVE_NACIONALIDAD' => 'DJI'],
            ['CODIGO_PAIS' => 'ZM', 'PAIS' => 'ZAMBIA', 'CLAVE_NACIONALIDAD' => 'ZMB'],
            ['CODIGO_PAIS' => 'ZW', 'PAIS' => 'ZIMBABUE', 'CLAVE_NACIONALIDAD' => 'ZWE']
        ];

        foreach (array_chunk($paises, 50) as $chunk) {
            DB::table('cat_paises')->insert($chunk);
        }
    }
}